apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: lifelog
  name: lifelog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lifelog
  template:
    metadata:
      labels:
        app: lifelog
    spec:
      containers:
        - name: lifelog
          image: ghcr.io/punsvikcloud/lifelog:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ConnectionStrings__Marten
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: connectionstring