name: Deploy .NET Aspire to Kubernetes Cluster with GHCR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted
    env:
      DOTNET_INSTALL_DIR: "/home/runner/.dotnet"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Aspirate
        run: dotnet tool install -g aspirate --prerelease

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}
          logout: true

      - name: Generate Kubernetes Manifests
        run: |
          cd LifeLog.AppHost
          aspirate init -cr ghcr.io -ct latest --disable-secrets true --non-interactive
          aspirate generate --image-pull-policy Always --non-interactive --disable-secrets --include-dashboard true

